### ISSUE TITLE
LabsPhi3_sk_rag01 fails

### ISSUE THREAD

**Issue by Barshan-Mandal** [microsoft/Phi-3CookBook#144]
`System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.ValueTuple`3<System.ReadOnlyMemory`1<Int64>,System.ReadOnlyMemory`1<Int64>,System.ReadOnlyMemory`1<Int64>> FastBertTokenizer.BertTokenizer.Encode(System.String, Int32, System.Nullable`1<Int32>)'.
  Source=SmartComponents.LocalEmbeddings
  StackTrace:
   at SmartComponents.LocalEmbeddings.LocalEmbedder.Embed[TEmbedding](String inputText, Nullable`1 outputBuffer, Int32 maximumTokens)
   at SmartComponents.LocalEmbeddings.LocalEmbedder.Embed(String inputText, Int32 maximumTokens)
   at SmartComponents.LocalEmbeddings.SemanticKernel.LocalTextEmbeddingGenerationService.GenerateEmbeddingsAsync(IList`1 data, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Embeddings.EmbeddingGenerationExtensions.<GenerateEmbeddingAsync>d__0`2.MoveNext()
   at Microsoft.SemanticKernel.Memory.SemanticTextMemory.<SaveInformationAsync>d__3.MoveNext()
   at phi3vision_aiconsole.Program.<Phi3MemoryRAG>d__2.MoveNext() in O:\Windows For Programming\Projects\Visual Studio\Console\Ai\phi3vision_aiconsole\Program.cs:line 86
   at phi3vision_aiconsole.Program.<Main>d__0.MoveNext() in O:\Windows For Programming\Projects\Visual Studio\Console\Ai\phi3vision_aiconsole\Program.cs:line 24
`

occurs at the following line

`
await memory.SaveInformationAsync(MemoryCollectionName, id: "info1", text: "Gisela's favourite super hero is Batman");
`

**Comment by leestott** [comment]
Hi @Barshan-Mandal  are you taking the semantic Kernel samples from https://github.com/elbruno/phi3-labs by @elbruno?

If so please raise issues on that repo?

**Comment by elbruno** [comment]
Hi
I'm working on update this sample to make it work again. In the meantime, you can refer to this post from Arafat, who performs a very similar scenario doing RAG in local mode.

https://arafattehsin.com/ai-copilot-offline-phi3-semantic-kernel/

Best

**Comment by Barshan-Mandal** [comment]
semantic text cant handle long books .try using kernel memory
