### ISSUE TITLE
Error when following "Inference Phi-3 in iOS" guide: 'pod-archive-onnxruntime-c-1.17.1.zip' Not Found

### ISSUE THREAD

**Issue by nobuhiroYamakado** [microsoft/Phi-3CookBook#55]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. Follow the [Inference Phi-3 in iOS](https://github.com/microsoft/Phi-3CookBook/blob/main/md/03.Inference/iOS_Inference.md) guide
2. Complete Step 2: Compiling ONNX Runtime for iOS
3. Proceed to Step 3: Compiling Generative AI with ONNX Runtime for iOS
4. Encounter BUILD FAILED error with message

### Any log messages given by the failure

```
CMake Error at onnxruntime-subbuild/onnxruntime-populate-prefix/src/onnxruntime-populate-stamp/download-onnxruntime-populate.cmake:162 (message):
  Each download failed!

    error: downloading 'https://onnxruntimepackages.z14.web.core.windows.net/pod-archive-onnxruntime-c-1.17.1.zip' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
          Host onnxruntimepackages.z14.web.core.windows.net:443 was resolved.
```

```
  using HTTP/1.x

  GET /pod-archive-onnxruntime-c-1.17.1.zip HTTP/1.1

  Host: onnxruntimepackages.z14.web.core.windows.net

  User-Agent: curl/8.4.0

  Accept: */*

  

  HTTP/1.1 404 The requested content does not exist.
```

<details>

<summary>Full log</summary>

```
% git clone https://github.com/microsoft/onnxruntime-genai

cd onnxruntime-genai

mkdir ort

cd ort

mkdir include

mkdir lib

cd ../

cp ../onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h ort/include

cp ../onnxruntime/build_ios/Release/Release-iphoneos/libonnxruntime*.dylib* ort/lib

export OPENCV_SKIP_XCODEBUILD_FORCE_TRYCOMPILE_DEBUG=1

python3 build.py --parallel --build_dir ./build_ios --ios --ios_sysroot iphoneos --ios_arch arm64 --ios_deployment_target 17.5 --cmake_generator Xcode --cmake_extra_defines CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO

Cloning into 'onnxruntime-genai'...
remote: Enumerating objects: 11907, done.
remote: Counting objects: 100% (1790/1790), done.
remote: Compressing objects: 100% (775/775), done.
remote: Total 11907 (delta 1033), reused 1567 (delta 924), pack-reused 10117
Receiving objects: 100% (11907/11907), 45.07 MiB | 14.58 MiB/s, done.
Resolving deltas: 100% (7440/7440), done.
2024-06-26 16:58:59,937 util.run [INFO] - Running subprocess in '/Users/my_name/Dev/onnxruntime-genai'
  /opt/homebrew/bin/cmake -G Xcode -DCMAKE_BUILD_TYPE=RelWithDebInfo -S /Users/my_name/Dev/onnxruntime-genai -B /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DUSE_CUDA=OFF -DUSE_ROCM=OFF -DUSE_DML=OFF -DENABLE_JAVA=OFF -DBUILD_WHEEL=ON -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=17.5 -DENABLE_PYTHON=OFF -DIOS_ARCH=arm64 -DIPHONEOS_DEPLOYMENT_TARGET=17.5 -DCMAKE_TOOLCHAIN_FILE=/Users/my_name/Dev/onnxruntime-genai/cmake/external/opencv/platforms/iOS/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
-- Setting up iPhoneOS toolchain for IOS_ARCH='arm64'
-- iPhoneOS toolchain loaded
-- Setting up iPhoneOS toolchain for IOS_ARCH='arm64'
-- iPhoneOS toolchain loaded
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Loading Dependencies URLs ...
Loading Dependencies ...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR=arm64
-- CMAKE_GENERATOR_PLATFORM=
-- ONNX Runtime URL: https://onnxruntimepackages.z14.web.core.windows.net/pod-archive-onnxruntime-c-1.17.1.zip
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project onnxruntime-populate.xcodeproj build -target ALL_BUILD -parallelizeTargets -configuration Debug -hideShellScriptEnvironment

User defaults from command line:
    HideShellScriptEnvironment = YES
    IDEPackageSupportUseBuiltinSCM = YES

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (3 targets)
    Target 'ALL_BUILD' in project 'onnxruntime-populate'
        ➜ Explicit dependency on target 'onnxruntime-populate' in project 'onnxruntime-populate'
        ➜ Explicit dependency on target 'ZERO_CHECK' in project 'onnxruntime-populate'
    Target 'onnxruntime-populate' in project 'onnxruntime-populate'
        ➜ Explicit dependency on target 'ZERO_CHECK' in project 'onnxruntime-populate'
    Target 'ZERO_CHECK' in project 'onnxruntime-populate' (no dependencies)

GatherProvisioningInputs

CreateBuildDescription

ExecuteExternalTool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -v -E -dM -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -x c -c /dev/null

Build description signature: b3c9c517ff63be342594c9004d51a0b2
Build description path: /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/XCBuildData/b3c9c517ff63be342594c9004d51a0b2.xcbuilddata
CreateBuildDirectory /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/onnxruntime-populate.xcodeproj
    builtin-create-build-directory /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build

CreateBuildDirectory /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/Debug
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/onnxruntime-populate.xcodeproj
    builtin-create-build-directory /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/Debug

CreateBuildDirectory /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/EagerLinkingTBDs/Debug
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/onnxruntime-populate.xcodeproj
    builtin-create-build-directory /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/EagerLinkingTBDs/Debug

note: Run script build phase 'Generate CMakeFiles/ZERO_CHECK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ZERO_CHECK' from project 'onnxruntime-populate')
WriteAuxiliaryFile /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/ZERO_CHECK.build/Script-37F6C704AEE63761E7EFCF00.sh (in target 'ZERO_CHECK' from project 'onnxruntime-populate')
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild
    write-file /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/ZERO_CHECK.build/Script-37F6C704AEE63761E7EFCF00.sh

PhaseScriptExecution Generate\ CMakeFiles/ZERO_CHECK /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/ZERO_CHECK.build/Script-37F6C704AEE63761E7EFCF00.sh (in target 'ZERO_CHECK' from project 'onnxruntime-populate')
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild
    /bin/sh -c /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/ZERO_CHECK.build/Script-37F6C704AEE63761E7EFCF00.sh
make: `/Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/CMakeFiles/cmake.check_cache' is up to date.

note: Run script build phase 'Generate CMakeFiles/onnxruntime-populate' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'onnxruntime-populate' from project 'onnxruntime-populate')
WriteAuxiliaryFile /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-D23A510593ECD8419139BF8A.sh (in target 'onnxruntime-populate' from project 'onnxruntime-populate')
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild
    write-file /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-D23A510593ECD8419139BF8A.sh

PhaseScriptExecution Generate\ onnxruntime-populate-prefix/src/onnxruntime-populate-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/onnxruntime-populate-mkdir /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-D23A510593ECD8419139BF8A.sh (in target 'onnxruntime-populate' from project 'onnxruntime-populate')
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild
    /bin/sh -c /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-D23A510593ECD8419139BF8A.sh

WriteAuxiliaryFile /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-F8219ED6C37AFCE5EA205F81.sh (in target 'onnxruntime-populate' from project 'onnxruntime-populate')
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild
    write-file /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-F8219ED6C37AFCE5EA205F81.sh

PhaseScriptExecution Generate\ onnxruntime-populate-prefix/src/onnxruntime-populate-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/onnxruntime-populate-download /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-F8219ED6C37AFCE5EA205F81.sh (in target 'onnxruntime-populate' from project 'onnxruntime-populate')
    cd /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild
    /bin/sh -c /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-F8219ED6C37AFCE5EA205F81.sh
-- Downloading...
   dst='/Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/onnxruntime-populate-prefix/src/pod-archive-onnxruntime-c-1.17.1.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://onnxruntimepackages.z14.web.core.windows.net/pod-archive-onnxruntime-c-1.17.1.zip'
-- [download 0% complete]
CMake Error at onnxruntime-subbuild/onnxruntime-populate-prefix/src/onnxruntime-populate-stamp/download-onnxruntime-populate.cmake:162 (message):
  Each download failed!

    error: downloading 'https://onnxruntimepackages.z14.web.core.windows.net/pod-archive-onnxruntime-c-1.17.1.zip' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
          Host onnxruntimepackages.z14.web.core.windows.net:443 was resolved.

  IPv6: (none)

  IPv4: 52.239.186.193

    Trying 52.239.186.193:443...

  Connected to onnxruntimepackages.z14.web.core.windows.net (52.239.186.193)
  port 443

  ALPN: curl offers h2,http/1.1

  (304) (OUT), TLS handshake, Client hello (1):

  [349 bytes data]

  (304) (IN), TLS handshake, Server hello (2):

  [88 bytes data]

  (304) (OUT), TLS handshake, Client hello (1):

  [414 bytes data]

  (304) (IN), TLS handshake, Server hello (2):

  [187 bytes data]

  (304) (IN), TLS handshake, Unknown (8):

  [6 bytes data]

  (304) (IN), TLS handshake, Certificate (11):

  [6500 bytes data]

  (304) (IN), TLS handshake, CERT verify (15):

  [264 bytes data]

  (304) (IN), TLS handshake, Finished (20):

  [52 bytes data]

  (304) (OUT), TLS handshake, Finished (20):

  [52 bytes data]

  SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 / [blank] / UNDEF

  ALPN: server did not agree on a protocol.  Uses default.

  Server certificate:

   subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=*.web.core.windows.net
   start date: Jun 19 08:45:30 2024 GMT
   expire date: Jun 14 08:45:30 2025 GMT
   subjectAltName: host "onnxruntimepackages.z14.web.core.windows.net" matched cert's "*.z14.web.core.windows.net"
   issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure RSA TLS Issuing CA 03
   SSL certificate verify ok.

  using HTTP/1.x

  GET /pod-archive-onnxruntime-c-1.17.1.zip HTTP/1.1

  Host: onnxruntimepackages.z14.web.core.windows.net

  User-Agent: curl/8.4.0

  Accept: */*

  

  HTTP/1.1 404 The requested content does not exist.

  Content-Length: 321

  Content-Type: text/html

  Server: Windows-Azure-Web/1.0 Microsoft-HTTPAPI/2.0

  x-ms-error-code: WebContentNotFound

  x-ms-request-id: eb7993ac-801e-00a1-3d9e-c7ef5a000000

  x-ms-version: 2018-03-28

  Date: Wed, 26 Jun 2024 07:59:43 GMT

  The requested URL returned error: 404

  Closing connection



          --- LOG END ---
          
    



note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'onnxruntime-populate')
** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution Generate\ onnxruntime-populate-prefix/src/onnxruntime-populate-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/onnxruntime-populate-download /Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo/_deps/onnxruntime-subbuild/build/onnxruntime-populate.build/Debug/onnxruntime-populate.build/Script-F8219ED6C37AFCE5EA205F81.sh (in target 'onnxruntime-populate' from project 'onnxruntime-populate')
(1 failure)

CMake Error at /opt/homebrew/Cellar/cmake/3.29.6/share/cmake/Modules/FetchContent.cmake:1714 (message):
  Build step for onnxruntime failed: 65
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.29.6/share/cmake/Modules/FetchContent.cmake:1854:EVAL:2 (__FetchContent_directPopulate)
  /opt/homebrew/Cellar/cmake/3.29.6/share/cmake/Modules/FetchContent.cmake:1854 (cmake_language)
  /opt/homebrew/Cellar/cmake/3.29.6/share/cmake/Modules/FetchContent.cmake:2081 (FetchContent_Populate)
  build_ios/RelWithDebInfo/_deps/onnxruntime_extensions-src/cmake/ext_ortlib.cmake:91 (FetchContent_makeAvailable)
  build_ios/RelWithDebInfo/_deps/onnxruntime_extensions-src/CMakeLists.txt:293 (include)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/Users/my_name/Dev/onnxruntime-genai/build.py", line 562, in <module>
    update(arguments, environment)
  File "/Users/my_name/Dev/onnxruntime-genai/build.py", line 501, in update
    util.run(command, env=env)
  File "/Users/my_name/Dev/onnxruntime-genai/tools/python/util/run.py", line 56, in run
    completed_process = subprocess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/homebrew/bin/cmake', '-G', 'Xcode', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-S', '/Users/my_name/Dev/onnxruntime-genai', '-B', '/Users/my_name/Dev/onnxruntime-genai/build_ios/RelWithDebInfo', '-DCMAKE_POSITION_INDEPENDENT_CODE=ON', '-DUSE_CUDA=OFF', '-DUSE_ROCM=OFF', '-DUSE_DML=OFF', '-DENABLE_JAVA=OFF', '-DBUILD_WHEEL=ON', '-DCMAKE_SYSTEM_NAME=iOS', '-DCMAKE_OSX_SYSROOT=iphoneos', '-DCMAKE_OSX_ARCHITECTURES=arm64', '-DCMAKE_OSX_DEPLOYMENT_TARGET=17.5', '-DENABLE_PYTHON=OFF', '-DIOS_ARCH=arm64', '-DIPHONEOS_DEPLOYMENT_TARGET=17.5', '-DCMAKE_TOOLCHAIN_FILE=/Users/my_name/Dev/onnxruntime-genai/cmake/external/opencv/platforms/iOS/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO']' returned non-zero exit status 1.
```

</details>

### Expected/desired behavior

Successfully compile that following all steps in the "Inference Phi-3 in iOS" guide without encountering any errors.

### OS and Version?

macOS Sonoma 14.5

### Versions

Xcode Version 15.4 (15F31d)
iOS SDK 17.5 
Python 3.10.11
cmake version 3.29.6

onnxruntime-genai commit: 2b240f5e715279c4abe000734f357d78ba8a0b2d
onnxruntime commit: e2abba18ea9370329ce6894a4eb3e98ad8f11cb6

### Mention any other details that might be useful

From what I can tell, the problem might be because the zip file we need isn't available at the `https://onnxruntimepackages.z14.web.core.windows.net/pod-archive-onnxruntime-c-1.17.1.zip` 

And this is come from onnxruntime-extensions: https://github.com/microsoft/onnxruntime-extensions/blob/f1abea14e88422a16e8337f86820bf306b506c61/cmake/ext_ortlib.cmake#L43

I'm not entirely sure if this is the right place to bring this up, but I'd really appreciate any tips or temporary solutions if anyone has them.

**Comment by nobuhiroYamakado** [comment]
I just checked again, and it's now accessible from all networks!
I'm not sure if it's related to the Azure LB issue _VRP-7DG, but after my previous post, I individually confirmed it was definitely returning a 404 from instances EC2 and Colaboratory. So I think it was a temporary problem.
Anyway, thank you. I'll close this issue.
